import type { AnalyzeResponse, Candidate, QualityFlag } from '../../types';
import { ChevronLeft, ChevronRight } from 'lucide-react';
import { Badge, DecisionBadge, format, Metric, readable, Section } from '../ui/Display';
import type { HumanReview } from '../../review/reviewStore';
import ReviewPanel from '../review/ReviewPanel';
import { locationState } from '../map/mapData';

type Props = { candidate: Candidate | null; index: number; result: AnalyzeResponse | null; review: HumanReview | undefined; onSaveReview: (review: HumanReview) => boolean; onDeleteReview: () => boolean; onNavigate: (offset: number) => void };
const short = (text: string) => text.length > 24 ? `${text.slice(0, 12)}…` : text;

function QualityFlags({ title, flags }: { title: string; flags: QualityFlag[] }) {
  return <div className="quality-group"><span>{title}</span>{flags.length ? flags.map((flag, index) => <div key={`${flag.code}-${index}`} className="quality-flag"><Badge status={flag.severity} /> {readable(flag.code)}</div>) : <strong>No flags reported</strong>}</div>;
}
function ProvenancePanel({ candidate }: { candidate: Candidate }) {
  return <details className="details"><summary>Provenance</summary><div className="details-content">{Object.entries(candidate.provenance).map(([key, value]) => <div className="data-row" key={key}><span>{readable(key)}</span><span className="mono" title={value ?? 'Not available'}>{value ? short(value) : 'Not available'}{value && value.length > 24 && <button type="button" className="copy" onClick={() => navigator.clipboard.writeText(value)} aria-label={`Copy full ${readable(key)}`}>COPY</button>}</span></div>)}</div></details>;
}

export default function AnalysisPanel({ candidate, index, result, review, onSaveReview, onDeleteReview, onNavigate }: Props) {
  if (!candidate) return <aside className="analysis-panel panel"><div className="panel-heading"><div><span className="eyebrow">CANDIDATE INSPECTION</span><h2>Sonar-Shield analysis</h2></div></div><div className="analysis-empty"><div className="sonar-glyph">◎</div><strong>{result && result.candidates.length === 0 ? 'NO CANDIDATES TO INSPECT' : 'SELECT A CANDIDATE'}</strong><span>{result && result.candidates.length === 0 ? 'The original image remains available in the viewer.' : 'Choose a detected object to inspect its backend-provided result.'}</span></div></aside>;
  const { detection, classification, decision, evidence, localization, localization_uncertainty: uncertainty, quality } = candidate;
  return <aside className="analysis-panel panel"><div className="panel-heading"><div><span className="eyebrow">CANDIDATE INSPECTION</span><h2>Sonar-Shield analysis</h2></div><div className="candidate-panel-nav"><button type="button" onClick={() => onNavigate(-1)} disabled={index <= 0} aria-label="Previous candidate"><ChevronLeft size={16} /></button><span className="mono muted">{index + 1} / {result?.candidates.length ?? 0}</span><button type="button" onClick={() => onNavigate(1)} disabled={index >= (result?.candidates.length ?? 0) - 1} aria-label="Next candidate"><ChevronRight size={16} /></button></div></div><div className="analysis-scroll">
    <div className="candidate-hero"><span className="eyebrow">AI ANALYSIS · CANDIDATE {String(index + 1).padStart(2, '0')} · {candidate.candidate_id}</span><h2>{detection.class_name}</h2><DecisionBadge status={decision.status} /><div className="hero-metrics"><Metric label="FUSION SCORE" value={decision.fusion_score} /><Metric label="AI CONFIDENCE" value={evidence.ai_confidence} /><Metric label="SOURCE" value={detection.source_mode} /></div></div>
    <Section title="Decision"><div className="decision-line"><DecisionBadge status={decision.status} /><span>Backend decision</span></div>{decision.reason_codes.length > 0 && <div className="reason-list">{decision.reason_codes.map(code => <span key={code}>{readable(code)}</span>)}</div>}</Section>
    <Section title="Detection"><div className="two-col"><Metric label="CLASS" value={detection.class_name} /><Metric label="SOURCE MODE" value={detection.source_mode} /><Metric label="AI CONFIDENCE" value={detection.confidence} /><Metric label="FUSION SCORE" value={decision.fusion_score} /><Metric label="BOX WIDTH" value={evidence.geometry?.width_px === undefined ? null : `${format(evidence.geometry.width_px)} px`} /><Metric label="BOX HEIGHT" value={evidence.geometry?.height_px === undefined ? null : `${format(evidence.geometry.height_px)} px`} /></div><div className="detection-reliability"><h4>BACKEND RELIABILITY</h4><div className="two-col"><Metric label="ESTIMATED TP RATE" value={classification.reliability?.estimated_tp_rate} /><Metric label="BAND" value={classification.presentation?.reliability_band} /><Metric label="CALIB SUPPORT" value={classification.reliability?.support_count} /><Metric label="UNCERTAINTY" value={classification.presentation?.uncertainty_level} /></div><p className="section-foot">{classification.reliability?.method ?? 'Method unavailable'} · {classification.reliability?.source_split ?? 'Source unavailable'}</p></div></Section>
    <Section title="Evidence"><div className="evidence-group"><h4>AI SIGNAL</h4><Metric label="Confidence" value={evidence.ai_confidence} /></div><div className="evidence-group"><h4>SONAR CONTEXT</h4><Metric label="Local contrast" value={evidence.seabed?.local_contrast} /><Metric label="Background mean" value={evidence.seabed?.background_mean} /><Metric label="Background std" value={evidence.seabed?.background_std} /></div><div className="evidence-group"><h4>GEOMETRY</h4><Metric label="Area px" value={evidence.geometry?.bbox_area_px} /><Metric label="Aspect ratio" value={evidence.geometry?.aspect_ratio} /></div><div className="evidence-group"><h4>SHADOW</h4><Metric label="Candidate presence" value={evidence.shadow?.shadow_candidate_presence} /><Metric label="Shadow area px" value={evidence.shadow?.shadow_area_px} /><Metric label="Area ratio" value={evidence.shadow?.area_ratio} /><Metric label="Adjacency" value={evidence.shadow?.adjacency} /></div><div className="evidence-group"><h4>BOUNDARY</h4><Metric label="Boundary strength" value={evidence.quality?.boundary_strength} /></div><div className="evidence-group"><h4>ARTIFACTS</h4>{Object.entries(evidence.quality?.artifact_flags ?? {}).length ? Object.entries(evidence.quality.artifact_flags).map(([key, value]) => <Metric key={key} label={readable(key)} value={value} />) : <p className="empty-note">Not available</p>}</div></Section>
    <Section title="Localization">{localization.physical_dimensions && <><Metric label="ESTIMATED WIDTH M" value={localization.physical_dimensions.width_m} /><Metric label="ESTIMATED HEIGHT M" value={localization.physical_dimensions.height_m} /><small>{localization.physical_dimensions.status}</small></>}<div className="capability"><Badge status={localization.metadata.status} /><span>{readable(localization.metadata.reason_code)}</span></div>{localization.coordinates.image && <div className="two-col"><Metric label="IMAGE X" value={localization.coordinates.image.center_x} /><Metric label="IMAGE Y" value={localization.coordinates.image.center_y} /></div>}{locationState(candidate) === 'GEOGRAPHIC' && localization.coordinates.geographic ? <><div className="two-col"><Metric label="LATITUDE" value={localization.coordinates.geographic.latitude} /><Metric label="LONGITUDE" value={localization.coordinates.geographic.longitude} /></div><button type="button" className="map-link" onClick={() => document.getElementById('geospatial')?.scrollIntoView({ behavior: 'smooth' })}>View on map</button></> : <div className="location-empty">GEOGRAPHIC LOCATION UNAVAILABLE<small>{locationState(candidate) === 'INVALID' ? 'Location data is invalid for map display.' : 'No valid geographic coordinates were returned.'}</small></div>}<div className="uncertainty"><h4>LOCALIZATION UNCERTAINTY</h4><Metric label="P90 ERROR ENVELOPE" value={uncertainty.error_envelope.envelope_px === null ? uncertainty.error_envelope.status : `${format(uncertainty.error_envelope.envelope_px)} px`} /><small>{uncertainty.error_envelope.scope} · Validation reference, not the measured error of this candidate.</small></div></Section>
    <Section title="Quality"><div className="quality-grid"><QualityFlags title="IMAGE" flags={quality.image.flags} /><QualityFlags title="DETECTION" flags={quality.detection.flags} /><QualityFlags title="EVIDENCE" flags={quality.evidence.flags} /><QualityFlags title="LOCALIZATION" flags={quality.localization.flags} /><QualityFlags title="METADATA" flags={quality.metadata.flags} /></div>{quality.evidence.completeness.missing.length > 0 && <p className="section-foot">Missing evidence: {quality.evidence.completeness.missing.join(', ')}</p>}</Section>
    {result && <ReviewPanel key={`${result.analysis_id}:${candidate.candidate_id}`} analysisId={result.analysis_id} candidate={candidate} review={review} onSave={onSaveReview} onDelete={onDeleteReview} />}
    <ProvenancePanel candidate={candidate} /><details className="details"><summary>Processing</summary><div className="details-content"><Metric label="ANALYSIS ID" value={result?.analysis_id} /><Metric label="PROCESSING STATUS" value={result?.processing.status} /><Metric label="PROCESSING TIME" value={result ? `${result.processing.processing_time_ms} ms` : null} /><Metric label="CANDIDATE COUNT" value={result?.summary.candidate_count} /><Metric label="PIPELINE VERSION" value={result?.processing.pipeline_version} /></div></details>
  </div></aside>;
}
