import { useEffect,useRef,useState } from 'react';
import { judgeDemo,seedJudgeDemo } from '../../shared/judge-demo.mjs';
import { analyzeSchema } from '../api/schema';
import type { AnalyzeResponse } from '../types';
import type { ResultSource } from '../reports/export';
import type { HumanReview } from '../review/reviewStore';
type Config={url:string;publishableKey:string;bucket:string};
type Entry={id:string;analysis_id:string;source:ResultSource;has_image:boolean;deleting:boolean;expires_at:string};
type Revision={candidate_id:string;revision:number;reviewer:string;status:HumanReview['status'];note:string;created_at:string};
type Props={analysis:AnalyzeResponse|null;imageSrc:string|null;source:ResultSource;reviews:Record<string,HumanReview>;onOpen:(analysis:AnalyzeResponse,image:Blob,source:ResultSource,reviews:HumanReview[])=>void};
export default function CloudRecords({analysis,imageSrc,source,reviews,onOpen}:Props){
 const [config,setConfig]=useState<Config|null>(null),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[token,setToken]=useState(''),[team,setTeam]=useState(''),[entries,setEntries]=useState<Entry[]>([]),[history,setHistory]=useState<Revision[]>([]),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 const [demoReady,setDemoReady]=useState(false),[demoSession,setDemoSession]=useState(false);
 const generation=useRef(0),controller=useRef<AbortController|null>(null),expiry=useRef(0);
 // This is a request generation, not a DOM ref: invalidate its latest value on unmount.
 // eslint-disable-next-line react-hooks/exhaustive-deps
 useEffect(()=>{const abort=new AbortController();void fetch('/api/records',{signal:abort.signal}).then(r=>r.ok?r.json():null).then(value=>{if(!abort.signal.aborted&&value?.url&&value?.publishableKey&&value.bucket==='sonar-records')setConfig(value);}).catch(()=>{});return()=>{abort.abort();generation.current++;controller.current?.abort();};},[]);
 const request=async(path:string,options:RequestInit={},storage=false,bearer=token)=>{
  if(!config)throw Error('Cloud records are not configured. Browser-local records still work.');
  if(!bearer||Date.now()>=expiry.current)throw Error('Sign in again; your cloud session expired.');
  const response=await fetch(storage?`${config.url}/storage/v1${path}`:'/api/records',{...options,redirect:'error',signal:controller.current?AbortSignal.any([controller.current.signal,AbortSignal.timeout(20000)]):AbortSignal.timeout(20000),headers:{...(storage?{apikey:config.publishableKey}:{}),...options.headers,Authorization:`Bearer ${bearer}`}});
  if(!response.ok){const value=await response.json().catch(()=>({}));throw Error(response.status===409?'Image or review already exists; reload before changing it.':typeof value.detail==='string'?value.detail:`Cloud request failed (${response.status}).`);}return response;
 };
 const api=async(body:object,bearer=token)=>request('',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)},false,bearer).then(r=>r.json());
 const perform=(action:(version:number)=>Promise<void>)=>{const version=++generation.current;controller.current?.abort();controller.current=new AbortController();setBusy(true);setMessage('');void action(version).catch(error=>{if(version===generation.current)setMessage(error instanceof Error?error.message:'Cloud operation failed.');}).finally(()=>{if(version===generation.current){setBusy(false);controller.current=null;}});};
 const listing=async(bearer=token)=>{const value=await api({action:'list'},bearer);if(!Array.isArray(value.records))throw Error('Invalid cloud record list.');setEntries(value.records);};
 useEffect(()=>{if(!config)return;const abort=new AbortController();void fetch(`${config.url}/rest/v1/rpc/sonar_judge_demo_ready`,{method:'POST',headers:{apikey:config.publishableKey,'Content-Type':'application/json'},body:'{}',signal:abort.signal,redirect:'error'}).then(r=>r.ok?r.json():false).then(value=>{if(!abort.signal.aborted)setDemoReady(value===true);}).catch(()=>{});return()=>abort.abort();},[config]);
 const login=async(loginEmail:string,loginPassword:string,version:number)=>{
  if(!config)return null;const response=await fetch(`${config.url}/auth/v1/token?grant_type=password`,{method:'POST',headers:{apikey:config.publishableKey,'Content-Type':'application/json'},body:JSON.stringify({email:loginEmail,password:loginPassword}),signal:controller.current?AbortSignal.any([controller.current.signal,AbortSignal.timeout(20000)]):AbortSignal.timeout(20000),redirect:'error'});
  const value=await response.json();if(!response.ok||typeof value.access_token!=='string'||!Number.isFinite(value.expires_in))throw Error('Sign-in failed. Check your invited account and password.');if(version!==generation.current)return null;
  setToken(value.access_token);expiry.current=Date.now()+value.expires_in*1000;setEmail(loginEmail);setPassword('');setTeam('');setEntries([]);setHistory([]);setDemoSession(loginEmail.toLowerCase()===judgeDemo.email);return value.access_token as string;
 };
 const openDemo=()=>perform(async(version)=>{
  const bearer=await login(judgeDemo.email,judgeDemo.password,version);if(!bearer||!config)return;
  const record=await seedJudgeDemo({api:body=>api(body,bearer),fetcher:(input,init)=>fetch(input,{...init,signal:controller.current?.signal}),upload:async(path,image,digest)=>{
   try{await request(`/object/${config.bucket}/${path}`,{method:'POST',headers:{'Content-Type':'image/jpeg','x-upsert':'false'},body:image},true,bearer);}catch(error){const existing=await request(`/object/authenticated/${config.bucket}/${path}`,{},true,bearer).then(r=>r.blob());const hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',await existing.arrayBuffer())),v=>v.toString(16).padStart(2,'0')).join('');if(hash!==digest)throw error;}
  }});
  if(version!==generation.current)return;await listing(bearer);setHistory(record.review_history);setMessage('Signed in as demo judge. Contact 105 and sample review history are ready. Open cloud record below; no inference ran.');
 });
 return <section className="panel shared-records"><details><summary>Cloud records and review history</summary><p>Optional Supabase sign-in for persistent records. Live analysis and verified examples need no reviewer login. Records are client-imported, not server-certified AI evidence.</p>
 {!config&&<p>Cloud storage has not been configured. Local save, restore and exports remain available.</p>}
 <aside className="judge-cloud-demo"><span className="eyebrow">PUBLIC JUDGE SANDBOX</span><h3>Try saved records and review history</h3><p>Shared demo account with a precomputed Contact 105 record and clearly labeled sample notes. Everyone can see demo reviews. Do not enter private information. No inference runs.</p><dl><div><dt>Email</dt><dd>{judgeDemo.email}</dd></div><div><dt>Demo password</dt><dd>{judgeDemo.password}</dd></div></dl><button className="secondary" type="button" disabled={busy||!config||!demoReady} onClick={openDemo}>Sign in as demo judge</button>{!demoReady&&<p>Demo cloud account is not activated yet. Verified examples remain available without login.</p>}</aside>
 <div className="cloud-credentials"><label>Reviewer email<input type="email" autoComplete="username" value={email} onChange={event=>setEmail(event.target.value)} /></label><label>Password<input type="password" autoComplete="current-password" value={password} onChange={event=>setPassword(event.target.value)} /></label></div>
 <div className="cloud-actions"><button className="secondary" type="button" disabled={busy||!config} onClick={()=>perform(async(version)=>{if(await login(email,password,version))setMessage('Signed in. Load cloud records to check your provisioned access.');})}>Sign in</button>
 <button className="secondary" type="button" onClick={()=>{generation.current++;controller.current?.abort();if(config&&token)void fetch(`${config.url}/auth/v1/logout`,{method:'POST',headers:{apikey:config.publishableKey,Authorization:`Bearer ${token}`},redirect:'error'}).catch(()=>{});setToken('');setDemoSession(false);setPassword('');setEntries([]);setHistory([]);setBusy(false);expiry.current=0;setMessage('Signed out. Browser credentials cleared.');}}>Sign out</button>
 <button className="secondary" type="button" disabled={busy||!token} onClick={()=>perform(async()=>{await listing();setMessage('Cloud records loaded.');})}>Load cloud records</button></div>
 <label className="cloud-team">Optional team ID<input disabled={demoSession} value={team} onChange={event=>setTeam(event.target.value)} placeholder="Leave empty for private records" /></label>
 <div className="cloud-actions"><button className="secondary" type="button" disabled={busy||!token||!analysis||!imageSrc||demoSession} onClick={()=>perform(async(version)=>{if(!analysis||!imageSrc||!config)return;const image=await fetch(imageSrc).then(r=>r.blob());if(!image.size||image.size>32*1024*1024)throw Error('Image exceeds the cloud record limit.');const digest=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',await image.arrayBuffer())),v=>v.toString(16).padStart(2,'0')).join('');const record=await api({action:'create',analysis,source,image_sha256:digest,image_bytes:image.size,image_mime:image.type,team_id:team||null});try{await request(`/object/${config.bucket}/${record.image_path}`,{method:'POST',headers:{'Content-Type':image.type,'x-upsert':'false'},body:image},true);}catch(error){const existing=await request(`/object/authenticated/${config.bucket}/${record.image_path}`,{},true).then(r=>r.blob());const hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',await existing.arrayBuffer())),v=>v.toString(16).padStart(2,'0')).join('');if(hash!==digest)throw error;}if(version===generation.current){await listing();setMessage('Analysis and paired image saved. Sync reviews explicitly below.');}})}>Save to cloud</button>
 <button className="secondary" type="button" disabled={busy||!token||!analysis} onClick={()=>perform(async()=>{if(!analysis)return;const list=await api({action:'list'});const matches=(list.records as Entry[]).filter(r=>r.analysis_id===analysis.analysis_id);if(matches.length>1)throw Error('Multiple cloud records share this analysis ID. Use a private record or a unique analysis before syncing reviews.');const entry=matches[0];if(!entry)throw Error('Save the analysis to cloud first.');const record=await api({action:'get',id:entry.id});const revisions:Revision[]=record.review_history;let count=0;for(const review of Object.values(reviews)){if(review.analysisId!==analysis.analysis_id)continue;const previous=revisions.filter(r=>r.candidate_id===review.candidateId).sort((a,b)=>b.revision-a.revision)[0];if(previous&&previous.status===review.status&&previous.note===review.note)continue;if(previous&&!window.confirm('A different cloud review exists. Save your assessment as a new revision?'))continue;await api({action:'review',id:entry.id,candidate_id:review.candidateId,previous_revision:previous?.revision??0,status:review.status,note:review.note});count++;}const latest=await api({action:'get',id:entry.id});setHistory(latest.review_history);setMessage(`${count} cloud review revisions saved.`);})}>Sync reviews to cloud</button></div>
 {demoSession&&<p className="judge-demo-session">DEMO REVIEWER · shared public notes · sample-only cloud access · 2,000 characters per review. Your private account is separate.</p>}
 <p className="cloud-operation-status" role="status">{busy?'Working...':message}</p><ul>{entries.map(entry=><li key={entry.id}>{entry.analysis_id}  -  {entry.source==='PRECOMPUTED_EXAMPLE'?'PRECOMPUTED EXAMPLE  -  NOT LIVE INFERENCE':'LIVE ANALYSIS'}  -  {entry.deleting?'deletion pending':entry.has_image?'paired image stored':'image missing'}  -  expires {entry.expires_at}
 <button className="secondary" type="button" disabled={busy||!entry.has_image||entry.deleting} onClick={()=>perform(async(version)=>{if(!config)return;const record=await api({action:'get',id:entry.id});const result=analyzeSchema.parse(record.analysis) as AnalyzeResponse;if(!['LIVE_ANALYSIS','PRECOMPUTED_EXAMPLE'].includes(record.source))throw Error('Invalid source label.');const image=await request(`/object/authenticated/${config.bucket}/${record.image_path}`,{},true).then(r=>r.blob());if(image.size>32*1024*1024)throw Error('Stored image exceeds limit.');const digest=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',await image.arrayBuffer())),v=>v.toString(16).padStart(2,'0')).join('');if(digest!==record.image_sha256)throw Error('Stored image pairing failed.');const bitmap=await createImageBitmap(image);const valid=bitmap.width===result.input.width&&bitmap.height===result.input.height&&bitmap.width*bitmap.height<=16_000_000;bitmap.close();if(!valid)throw Error('Stored image dimensions are invalid.');const latest=new Map<string,Revision>();for(const revision of record.review_history as Revision[])if(!latest.has(revision.candidate_id)||(latest.get(revision.candidate_id)?.revision??0)<revision.revision)latest.set(revision.candidate_id,revision);if(version!==generation.current)return;setHistory(record.review_history);onOpen(result,image,record.source,[...latest.values()].map(r=>({analysisId:result.analysis_id,candidateId:r.candidate_id,status:r.status,note:r.note,reviewedAt:r.created_at})));setMessage('Cloud record opened. No inference ran.');})}>Open cloud record</button>
 <button className="secondary record-danger" type="button" disabled={busy||demoSession} onClick={()=>{if(!window.confirm('Delete the cloud image, analysis and all review history?'))return;perform(async()=>{if(!config)return;const value=await api({action:'delete_begin',id:entry.id});await request(`/object/${config.bucket}`,{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({prefixes:[value.image_path]})},true);await api({action:'delete_finish',id:entry.id});await listing();setMessage('Cloud record, image and history deleted.');});}}>Delete cloud record</button></li>)}</ul>
 {history.length>0&&<details><summary>Cloud review revision history</summary><ul>{history.map(r=><li key={`${r.candidate_id}-${r.revision}`}>{r.candidate_id}  -  revision {r.revision}  -  reviewer {r.reviewer}  -  {r.status}<p>{r.note}</p></li>)}</ul></details>}
 </details></section>;
}
