"""Self-contained offline window viewer; explicit local inference, no network calls."""
import base64
import json
from pathlib import Path


def write_viewer(output,index,response):
    output=Path(output)
    image=base64.b64encode((output/f'window-{index:05d}.png').read_bytes()).decode()
    payload=json.dumps(response,allow_nan=False).replace('<','\\u003c').replace('>','\\u003e').replace('&','\\u0026')
    template='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>SONAR-SHIELD offline survey review</title>
<style>body{background:#08151d;color:#e5f5fa;font:16px system-ui;margin:24px}header{border-bottom:2px solid #59c9dd;padding:12px}button,select,textarea{font:inherit;margin:8px;padding:8px}button{cursor:pointer}.layout{display:grid;grid-template-columns:2fr 1fr;gap:20px}svg{width:100%;background:#000}rect{stroke:#ffcf60;fill:transparent;stroke-width:2;cursor:pointer}pre{white-space:pre-wrap;overflow-wrap:anywhere}textarea{width:85%;height:90px}.label{color:#ffcf60;font-weight:bold}@media(max-width:800px){.layout{display:block}}@media print{button,select,textarea{display:none}body{background:white;color:black}.label{color:black}svg{max-height:500px}}</style>
<header><h1>SONAR-SHIELD survey window __INDEX__</h1><p class="label">LOCAL OFFLINE INFERENCE Â· OPENING THIS FILE RUNS NO INFERENCE</p><p>Detector decisions remain REVIEW. Confidence is not calibrated accuracy. Positions and dimensions are estimates only when explicit geometry is supplied; field accuracy is not verified.</p><a href="report.csv">Survey CSV</a> Â· <a href="report.json">Survey JSON</a> Â· <a href="contacts.geojson">Geographic observations</a></header>
<div class="layout"><main><p id="summary"></p><svg id="viewer"><image id="image" href="data:image/png;base64,__IMAGE__"/></svg><div id="buttons"></div><h2>Candidate positions · WGS84</h2><p id="map-status">No verified geometry supplied; geographic map unavailable.</p><svg id="position-map" viewBox="0 0 400 260" role="img" aria-label="Candidate geographic positions, without a basemap" style="max-height:300px" hidden></svg></main><aside><h2>Candidate and evidence</h2><pre id="detail">Select a candidate.</pre><label>Human review<select id="status"><option>NEEDS_INVESTIGATION</option><option>CONFIRMED</option><option>FALSE_POSITIVE</option></select></label><label>Review note<textarea id="note"></textarea></label><button id="save">Save human review</button><button id="export">Export analysis + human reviews</button><button onclick="window.print()">Print</button><p id="message" role="status"></p></aside></div>
<script type="application/json" id="data">__PAYLOAD__</script><script>
'use strict';const analysis=JSON.parse(document.getElementById('data').textContent),viewer=document.getElementById('viewer'),image=document.getElementById('image'),detail=document.getElementById('detail'),message=document.getElementById('message');
const key='sonar-offline-review:'+analysis.analysis_id;let reviews={},selected=null;try{reviews=JSON.parse(localStorage.getItem(key)||'{}')}catch{message.textContent='Browser persistence unavailable. Export reviews before closing.'}
viewer.setAttribute('viewBox',`0 0 ${analysis.input.width} ${analysis.input.height}`);image.setAttribute('width',analysis.input.width);image.setAttribute('height',analysis.input.height);
document.getElementById('summary').textContent=`${analysis.candidates.length} candidate observations Â· ${analysis.survey_reference.navigation_status}`;
function select(c){selected=c;detail.textContent=JSON.stringify({detection:c.detection,decision:c.decision,classification:c.classification,evidence:c.evidence,localization:c.localization,quality:c.quality,provenance:c.provenance},null,2);document.getElementById('status').value=reviews[c.candidate_id]?.status||'NEEDS_INVESTIGATION';document.getElementById('note').value=reviews[c.candidate_id]?.note||''}
for(const c of analysis.candidates){const box=c.detection.bbox,r=document.createElementNS('http://www.w3.org/2000/svg','rect');for(const [k,v] of Object.entries({x:box[0],y:box[1],width:box[2]-box[0],height:box[3]-box[1]}))r.setAttribute(k,v);r.addEventListener('click',()=>select(c));viewer.append(r);const b=document.createElement('button');b.textContent=c.detection.class_name+' Â· '+c.candidate_id;b.addEventListener('click',()=>select(c));document.getElementById('buttons').append(b)}
const positions=analysis.candidates.map(c=>({c,p:c.localization?.coordinates?.geographic})).filter(v=>v.p&&Number.isFinite(v.p.latitude)&&Number.isFinite(v.p.longitude)&&Math.abs(v.p.latitude)<=90&&Math.abs(v.p.longitude)<=180);
if(positions.length){const map=document.getElementById('position-map'),lat0=positions.reduce((s,v)=>s+v.p.latitude,0)/positions.length,lon0=positions[0].p.longitude,cos=Math.cos(lat0*Math.PI/180),xy=positions.map(v=>({v,x:((v.p.longitude-lon0+540)%360-180)*cos,y:-(v.p.latitude-lat0)}));const xs=xy.map(v=>v.x),ys=xy.map(v=>v.y),xmin=Math.min(...xs),xmax=Math.max(...xs),ymin=Math.min(...ys),ymax=Math.max(...ys),scale=Math.min(340/Math.max(xmax-xmin,1e-6),200/Math.max(ymax-ymin,1e-6));map.hidden=false;map.style.display='block';document.getElementById('map-status').textContent=positions.length+' estimated candidate positions; field accuracy unverified. Local extent view, no basemap. Select a point to inspect its evidence.';for(const point of xy){const circle=document.createElementNS('http://www.w3.org/2000/svg','circle');circle.setAttribute('cx',200+(point.x-(xmin+xmax)/2)*scale);circle.setAttribute('cy',130+(point.y-(ymin+ymax)/2)*scale);circle.setAttribute('r',7);circle.setAttribute('fill','#66cde2');circle.setAttribute('tabindex','0');circle.setAttribute('role','button');circle.setAttribute('aria-label',point.v.c.candidate_id+' latitude '+point.v.p.latitude+' longitude '+point.v.p.longitude);circle.addEventListener('click',()=>select(point.v.c));circle.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();select(point.v.c)}});const title=document.createElementNS('http://www.w3.org/2000/svg','title');title.textContent=point.v.c.candidate_id+' · '+point.v.p.latitude+', '+point.v.p.longitude;circle.append(title);map.append(circle)}}
document.getElementById('save').onclick=()=>{if(!selected){message.textContent='Select a candidate first.';return}const note=document.getElementById('note').value;if(note.length>2000){message.textContent='Review notes must be at most 2000 characters.';return}reviews[selected.candidate_id]={status:document.getElementById('status').value,note,reviewed_at:new Date().toISOString()};try{localStorage.setItem(key,JSON.stringify(reviews));message.textContent='Human review saved in this browser. Original AI result unchanged.'}catch{message.textContent='Review retained in memory only; export it before closing.'}};
document.getElementById('export').onclick=()=>{const blob=new Blob([JSON.stringify({source:'LOCAL_RAW_SURVEY_INFERENCE',source_label:'LOCAL OFFLINE INFERENCE Â· NOT A NEW HF RUN',calibration:'UNAVAILABLE',field_accuracy:'NOT_EVALUATED',analysis,human_reviews:reviews},null,2)],{type:'application/json'}),a=document.createElement('a'),url=URL.createObjectURL(blob);a.href=url;a.download='survey-window-__INDEX__-review.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
</script></html>'''
    template=template.replace('__INDEX__',str(index)).replace('__IMAGE__',image).replace('__PAYLOAD__',payload)
    (output/f'window-{index:05d}.html').write_text(template,encoding='utf-8')
