"""Self-contained offline window viewer; explicit local inference, no network calls."""
import base64
import json
from pathlib import Path


def write_viewer(output,index,response):
    output=Path(output)
    preview=output/f'window-{index:05d}-preview.png'
    image=base64.b64encode((preview if preview.exists() else output/f'window-{index:05d}.png').read_bytes()).decode()
    display_notice='Contrast preview only. Existing analysis was run on the original image; this preview is not a new analysis.' if preview.exists() else 'Recorded amplitude conversion is unvalidated for detector performance. Pixel coordinates refer to the analyzed image.'
    payload=json.dumps(response,allow_nan=False).replace('<','\\u003c').replace('>','\\u003e').replace('&','\\u0026')
    template='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>SONAR-SHIELD offline survey review</title>
<style>*{box-sizing:border-box}body{background:#08131b;color:#e9f3f6;font:13px system-ui;margin:0;padding:24px}header,.layout{max-width:1600px;margin:auto}header{background:#0e202a;border:1px solid #2b4551;border-radius:8px;padding:20px;margin-bottom:18px}h1{font-size:24px;margin:0 0 12px}h2{font-size:16px;margin:18px 0 12px}p{line-height:1.65;color:#a6bdc7}a{color:#66cde2;text-decoration:none;display:inline-block;padding:8px 10px;border:1px solid #456b7b;border-radius:4px;margin:4px 6px 4px 0}a:hover{background:#193743}button,select,textarea{font:inherit;background:#142a35;color:#e9f3f6;border:1px solid #456b7b;border-radius:4px;padding:10px}button{cursor:pointer;margin:6px 8px 6px 0;min-height:38px}button:disabled,select:disabled,textarea:disabled{opacity:.45;cursor:not-allowed}button:focus-visible,a:focus-visible,select:focus-visible,textarea:focus-visible{outline:2px solid #66cde2;outline-offset:2px}.layout{display:grid;grid-template-columns:minmax(0,2fr) minmax(280px,1fr);gap:18px;align-items:start}main,aside{min-width:0;background:#0e202a;border:1px solid #2b4551;border-radius:8px;padding:16px}.image-shell{height:clamp(260px,48vh,480px);background:#000;border:1px solid #2b4551;overflow:auto;border-radius:5px}#viewer{width:100%;height:100%;display:block}#position-map{width:100%;height:260px;background:#091923;border:1px solid #2b4551;border-radius:5px}#position-map[hidden]{display:none!important}rect{stroke:#ffcf60;fill:transparent;stroke-width:2;vector-effect:non-scaling-stroke;cursor:pointer}pre{font:11px Consolas,monospace;white-space:pre-wrap;overflow-wrap:anywhere;max-height:460px;overflow:auto;background:#08131b;border-radius:4px;padding:12px;line-height:1.6}label{display:grid;gap:8px;margin:14px 0;color:#a6bdc7}textarea{width:100%;min-height:100px;resize:vertical}.label{color:#e7bb77;font-size:11px;font-weight:bold;letter-spacing:.05em}.viewer-actions{display:flex;flex-wrap:wrap;align-items:center;gap:8px}.viewer-actions button{margin:0}.display-note{font-size:11px}.empty-state{padding:16px;background:#142a35;border-radius:4px}.map-wrapper{margin-top:18px}.native-aspect #viewer{height:auto;aspect-ratio:var(--raster-ratio)}@media(max-width:1000px){.layout{grid-template-columns:1fr}body{padding:14px}h1{font-size:21px}pre{max-height:300px}}@media print{button,select,textarea,.viewer-actions{display:none}body{background:white;color:black}.label,p{color:black}.layout{display:block}header,main,aside{background:white;color:black;border-color:#aaa}pre{max-height:none;background:white;color:black}.image-shell{height:350px}}</style>
<header><a href="index.html">Back to survey</a><h1>SONAR-SHIELD survey window __INDEX__</h1><p class="label">LOCAL OFFLINE INFERENCE  |  OPENING THIS FILE RUNS NO INFERENCE</p><p>Detector decisions remain REVIEW. Confidence is not calibrated accuracy. Positions and dimensions are estimates only when explicit geometry is supplied; field accuracy is not verified.</p><a href="report.csv">Survey CSV</a>  |  <a href="report.json">Survey JSON</a>  |  <a href="contacts.geojson">Geographic observations</a></header>
<div class="layout"><main><p id="summary"></p><div class="viewer-actions"><button id="aspect" type="button">Show native pixel aspect</button><span class="display-note">Inspection view scales ping rows and sample columns independently.</span></div><p class="display-note">__DISPLAY_NOTICE__</p><div class="image-shell" id="image-shell"><svg id="viewer" preserveAspectRatio="none"><image id="image" preserveAspectRatio="none" href="data:image/png;base64,__IMAGE__"/></svg></div><div id="buttons"></div><h2>Candidate positions  |  WGS84</h2><p id="map-status">No verified geometry supplied; geographic map unavailable.</p><svg id="position-map" viewBox="0 0 400 260" role="img" aria-label="Candidate geographic positions, without a basemap" style="max-height:300px" hidden></svg></main><aside><h2>Candidate and evidence</h2><p id="candidate-summary" class="empty-state">Select a candidate box or button to inspect it.</p><details><summary>Evidence and technical details</summary><pre id="detail">Select a candidate.</pre></details><label>Human review<select id="status"><option>NEEDS_INVESTIGATION</option><option>CONFIRMED</option><option>FALSE_POSITIVE</option></select></label><label>Review note<textarea id="note"></textarea></label><button id="save">Save human review</button><button id="export">Export analysis + human reviews</button><button onclick="window.print()">Print</button><p id="message" role="status"></p></aside></div>
<script type="application/json" id="data">__PAYLOAD__</script><script>
'use strict';const analysis=JSON.parse(document.getElementById('data').textContent),viewer=document.getElementById('viewer'),image=document.getElementById('image'),detail=document.getElementById('detail'),message=document.getElementById('message');
const key='sonar-offline-review:'+analysis.analysis_id;let reviews={},selected=null;try{reviews=JSON.parse(localStorage.getItem(key)||'{}')}catch{message.textContent='Browser persistence unavailable. Export reviews before closing.'}
viewer.setAttribute('viewBox',`0 0 ${analysis.input.width} ${analysis.input.height}`);image.setAttribute('width',analysis.input.width);image.setAttribute('height',analysis.input.height);
document.getElementById('aspect').onclick=()=>{const shell=document.getElementById('image-shell'),native=shell.classList.toggle('native-aspect');shell.style.setProperty('--raster-ratio',analysis.input.width+'/'+analysis.input.height);document.getElementById('aspect').textContent=native?'Show expanded ping rows':'Show native pixel aspect'};
for(const id of ['status','note','save'])document.getElementById(id).disabled=true;
if(!analysis.candidates.length){document.getElementById('candidate-summary').textContent='No candidates were detected in this window. This is not evidence that the complete survey contains no debris.';detail.textContent='No candidate evidence is available.';message.textContent='Human review requires a detected candidate. Image inspection and exports remain available.'}
document.getElementById('summary').textContent=`${analysis.candidates.length} candidate observations  |  ${analysis.survey_reference.navigation_status}`;
function select(c){selected=c;document.getElementById('candidate-summary').textContent=c.detection.class_name+' | Detector score '+(100*c.detection.confidence).toFixed(1)+'% | Machine decision '+c.decision.status+' | Calibration unavailable. Human assessment is recorded separately.';for(const id of ['status','note','save'])document.getElementById(id).disabled=false;detail.textContent=JSON.stringify({detection:c.detection,decision:c.decision,classification:c.classification,evidence:c.evidence,localization:c.localization,quality:c.quality,provenance:c.provenance},null,2);document.getElementById('status').value=reviews[c.candidate_id]?.status||'NEEDS_INVESTIGATION';document.getElementById('note').value=reviews[c.candidate_id]?.note||''}
for(const c of analysis.candidates){const box=c.detection.bbox,r=document.createElementNS('http://www.w3.org/2000/svg','rect');for(const [k,v] of Object.entries({x:box[0],y:box[1],width:box[2]-box[0],height:box[3]-box[1]}))r.setAttribute(k,v);r.addEventListener('click',()=>select(c));viewer.append(r);const b=document.createElement('button');b.textContent=c.detection.class_name+'  |  '+c.candidate_id;b.addEventListener('click',()=>select(c));document.getElementById('buttons').append(b)}
const positions=analysis.candidates.map(c=>({c,p:c.localization?.coordinates?.geographic})).filter(v=>v.p&&Number.isFinite(v.p.latitude)&&Number.isFinite(v.p.longitude)&&Math.abs(v.p.latitude)<=90&&Math.abs(v.p.longitude)<=180);
if(positions.length){const map=document.getElementById('position-map'),lat0=positions.reduce((s,v)=>s+v.p.latitude,0)/positions.length,lon0=positions[0].p.longitude,cos=Math.cos(lat0*Math.PI/180),xy=positions.map(v=>({v,x:((v.p.longitude-lon0+540)%360-180)*cos,y:-(v.p.latitude-lat0)}));const xs=xy.map(v=>v.x),ys=xy.map(v=>v.y),xmin=Math.min(...xs),xmax=Math.max(...xs),ymin=Math.min(...ys),ymax=Math.max(...ys),scale=Math.min(340/Math.max(xmax-xmin,1e-6),200/Math.max(ymax-ymin,1e-6));map.removeAttribute('hidden');map.style.display='block';document.getElementById('map-status').textContent=positions.length+' estimated candidate positions; field accuracy unverified. Local extent view, no basemap. Select a point to inspect its evidence.';for(const point of xy){const circle=document.createElementNS('http://www.w3.org/2000/svg','circle');circle.setAttribute('cx',200+(point.x-(xmin+xmax)/2)*scale);circle.setAttribute('cy',130+(point.y-(ymin+ymax)/2)*scale);circle.setAttribute('r',7);circle.setAttribute('fill','#66cde2');circle.setAttribute('tabindex','0');circle.setAttribute('role','button');circle.setAttribute('aria-label',point.v.c.candidate_id+' latitude '+point.v.p.latitude+' longitude '+point.v.p.longitude);circle.addEventListener('click',()=>select(point.v.c));circle.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();select(point.v.c)}});const title=document.createElementNS('http://www.w3.org/2000/svg','title');title.textContent=point.v.c.candidate_id+'  |  '+point.v.p.latitude+', '+point.v.p.longitude;circle.append(title);map.append(circle)}}
document.getElementById('save').onclick=()=>{if(!selected){message.textContent='Select a candidate first.';return}const note=document.getElementById('note').value;if(note.length>2000){message.textContent='Review notes must be at most 2000 characters.';return}reviews[selected.candidate_id]={status:document.getElementById('status').value,note,reviewed_at:new Date().toISOString()};try{localStorage.setItem(key,JSON.stringify(reviews));message.textContent='Human review saved in this browser. Original AI result unchanged.'}catch{message.textContent='Review retained in memory only; export it before closing.'}};
document.getElementById('export').onclick=()=>{const blob=new Blob([JSON.stringify({source:'LOCAL_RAW_SURVEY_INFERENCE',source_label:'LOCAL OFFLINE INFERENCE  |  NOT A NEW HF RUN',calibration:'UNAVAILABLE',field_accuracy:'NOT_EVALUATED',analysis,human_reviews:reviews},null,2)],{type:'application/json'}),a=document.createElement('a'),url=URL.createObjectURL(blob);a.href=url;a.download='survey-window-__INDEX__-review.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
</script></html>'''
    template=template.replace('__DISPLAY_NOTICE__',display_notice).replace('__INDEX__',str(index)).replace('__IMAGE__',image).replace('__PAYLOAD__',payload)
    (output/f'window-{index:05d}.html').write_text(template,encoding='utf-8')


def write_index(output,state):
    import html
    output=Path(output);cards=[]
    for index in range(state['windows_completed']):
        if not (output/f'window-{index:05d}.html').exists():continue
        response=json.loads((output/f'window-{index:05d}.json').read_text(encoding='utf-8'))
        reference=response['survey_reference'];count=len(response['candidates'])
        preview=output/f'window-{index:05d}-preview.png'
        image=preview.name if preview.exists() else f'window-{index:05d}.png'
        cards.append(f'<a class="window" href="window-{index:05d}.html"><img alt="Survey window {index} preview" src="{image}"><strong>Window {index}</strong><span>Channel {reference["channel"]} | {count} candidates | {response["input"]["width"]} x {response["input"]["height"]} px</span><span>Open image, evidence and human review</span></a>')
    markup='<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>SONAR-SHIELD survey results</title><style>*{box-sizing:border-box}body{margin:0;padding:24px;background:#08131b;color:#e9f3f6;font:13px system-ui}main{max-width:1500px;margin:auto}h1{font-size:24px}.panel{background:#0e202a;border:1px solid #2b4551;border-radius:8px;padding:20px;margin:16px 0}p,span{color:#a6bdc7;line-height:1.65}a{color:#66cde2}nav{display:flex;flex-wrap:wrap;gap:10px}nav a{padding:10px 13px;border:1px solid #456b7b;border-radius:4px;text-decoration:none}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,280px),1fr));gap:16px}.window{background:#0e202a;border:1px solid #2b4551;border-radius:8px;padding:16px;text-decoration:none;display:grid;gap:10px}.window:hover{border-color:#66cde2}.window img{width:100%;height:160px;object-fit:fill;background:black;border-radius:4px}strong{font-size:16px}@media(max-width:600px){body{padding:14px}}</style><main><header class="panel"><p>LOCAL RAW SURVEY INFERENCE</p><h1>Survey results</h1><p>Opening these results runs no inference. Each window is a bounded section, not the entire survey. Calibration is unavailable; geographic estimates require explicit reviewed geometry.</p><p>Status: '+html.escape(state['status'])+' | Completed windows: '+str(state['windows_completed'])+'</p><nav><a href="report.csv">CSV report</a><a href="report.json">JSON report</a><a href="contacts.geojson">Geographic observations</a></nav></header><section class="grid">'+''.join(cards)+'</section></main></html>'
    (output/'index.html').write_text(markup,encoding='utf-8')
