import test from 'node:test';import assert from 'node:assert/strict';import {EventEmitter} from 'node:events';import {readFileSync} from 'node:fs';
import {configuration,acquireSupabaseAdmission} from '../server/supabase.mjs';import {createRecordsHandler} from '../server/records.mjs';import {createMaintenance} from '../server/maintenance.mjs';
const env={SUPABASE_URL:'https://project.supabase.co',SUPABASE_PUBLISHABLE_KEY:'sb_publishable_TEST_ONLY_0123456789',SUPABASE_SECRET_KEY:'sb_secret_TEST_ONLY_012345678901234',APP_ORIGIN:'https://sonarshield26.vercel.app',NODE_ENV:'production',CRON_SECRET:'TEST_CRON_ONLY_01234567890123456789'};
const jwt='TEST_USER_JWT_ONLY_0123456789';const id='11111111-1111-1111-1111-111111111111';
async function invoke(handler,body,headers={},method='POST'){const res=new EventEmitter();res.setHeader=()=>{};res.end=text=>{res.value=JSON.parse(text);};await handler({method,headers:{origin:env.APP_ORIGIN,'sec-fetch-site':'same-origin','content-type':'application/json',authorization:`Bearer ${jwt}`,...headers},body},res);return res;}
test('public configuration rejects secret keys and never returns credentials',async()=>{assert.throws(()=>configuration({...env,SUPABASE_PUBLISHABLE_KEY:env.SUPABASE_SECRET_KEY}));const res=await invoke(createRecordsHandler({env}),undefined,{},'GET');assert.equal(res.statusCode,200);assert.equal(res.value.publishableKey,env.SUPABASE_PUBLISHABLE_KEY);assert.ok(!JSON.stringify(res.value).includes(env.SUPABASE_SECRET_KEY));});
test('records verify user with HF-free traffic, reject foreign origin and never use service secret',async()=>{const calls=[];const fetcher=async(url,options)=>{calls.push({url,options});return new Response(JSON.stringify(url.endsWith('/user')?{id}:{records:[]}));};const handler=createRecordsHandler({env,fetcher});assert.equal((await invoke(handler,{action:'list'})).statusCode,200);assert.equal(calls.length,2);assert.ok(calls.every(c=>!JSON.stringify(c.options).includes(env.SUPABASE_SECRET_KEY)));calls.length=0;assert.equal((await invoke(handler,{action:'list'},{origin:'https://evil.invalid'})).statusCode,403);assert.equal(calls.length,0);});
test('invalid/revoked reviewer, malformed records and review conflicts return controlled errors',async()=>{const revoked=createRecordsHandler({env,fetcher:async()=>new Response('{}',{status:401})});assert.equal((await invoke(revoked,{action:'list'})).statusCode,401);const mock=async url=>new Response(JSON.stringify(url.endsWith('/user')?{id}:{code:'23505'}),{status:url.endsWith('/user')?200:409});const handler=createRecordsHandler({env,fetcher:mock});assert.equal((await invoke(handler,{action:'arbitrary_rpc'})).statusCode,422);const analysis=JSON.parse(readFileSync(new URL('../public/contact-105.json',import.meta.url)));assert.equal((await invoke(handler,{action:'create',analysis,source:'PRECOMPUTED_EXAMPLE',image_sha256:analysis.input.sha256,image_bytes:66818,image_mime:'image/jpeg'})).statusCode,409);});
test('Supabase admission uses service key only on server RPC, fails closed and releases lease',async()=>{const calls=[];const fetcher=async(url,options)=>{calls.push({url,options});return new Response(JSON.stringify({lease_id:'a'.repeat(32)}));};const lease=await acquireSupabaseAdmission(env,fetcher);await lease.release();assert.equal(calls.length,2);assert.equal(calls[0].options.headers.apikey,env.SUPABASE_SECRET_KEY);await assert.rejects(acquireSupabaseAdmission(env,async()=>new Response(JSON.stringify({code:'P0001'}),{status:400})),e=>e.code==='LIVE_USAGE_LIMIT');await assert.rejects(acquireSupabaseAdmission(env,async()=>{throw Error('offline');}),e=>e.code==='LIVE_LIMITER_UNAVAILABLE');});
test('retention requires private cron credential and deletes storage before rows',async()=>{const order=[];const fetcher=async url=>{order.push(url);return new Response(JSON.stringify(url.endsWith('sonar_expired_records')?[{id,image_path:`${id}/${id}/image.jpg`}]:[]));};const handler=createMaintenance({env,fetcher});assert.equal((await invoke(handler,undefined,{},'GET')).statusCode,401);assert.equal(order.length,0);const res=await invoke(handler,undefined,{authorization:`Bearer ${env.CRON_SECRET}`},'GET');assert.equal(res.value.removed,1);assert.match(order[1],/storage/);assert.match(order[2],/sonar_prune_record/);});
