import { PGlite } from '../.temp/supabase-sql-test/node_modules/@electric-sql/pglite/dist/index.js';
import { readFileSync } from 'node:fs';
import assert from 'node:assert/strict';
const db=new PGlite();
await db.exec(`create role anon;create role authenticated;create role service_role;create schema auth;create schema storage;
create table auth.users(id uuid primary key);create function auth.uid() returns uuid language sql as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
grant usage on schema auth,storage to authenticated;grant execute on function auth.uid() to authenticated;
create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
create table storage.objects(bucket_id text,name text,primary key(bucket_id,name));alter table storage.objects enable row level security;grant select,insert,delete on storage.objects to authenticated;`);
await db.exec(readFileSync('supabase/migrations/202610020001_sonar_cloud.sql','utf8'));
const a='11111111-1111-1111-1111-111111111111',b='22222222-2222-2222-2222-222222222222';
await db.exec(`insert into auth.users values('${a}'),('${b}');insert into public.sonar_members values('${a}'),('${b}');`);
const sample=JSON.parse(readFileSync('frontend/public/contact-105.json','utf8'));
async function identity(id,role='authenticated'){await db.exec(`reset role;select set_config('request.jwt.claim.sub','${id}',false);set role ${role};`);}
await identity(a);
const result=await db.query('select public.sonar_record_create($1::jsonb,$2,$3,$4,$5,null) as value',[JSON.stringify(sample),'PRECOMPUTED_EXAMPLE',sample.input.sha256,66818,'image/jpeg']);
const record=result.rows[0].value;assert.equal(record.analysis.analysis_id,sample.analysis_id);
await db.query('insert into storage.objects values($1,$2)',['sonar-records',record.image_path]);
await assert.rejects(db.exec("insert into public.sonar_records(id) values(gen_random_uuid())"));
await identity(b);assert.equal((await db.query('select public.sonar_record_list() as value')).rows[0].value.records.length,0);
assert.equal((await db.query('select * from storage.objects')).rows.length,0);
await assert.rejects(db.query('insert into storage.objects values($1,$2)',['sonar-records',record.image_path+'/other']));
await assert.rejects(db.exec('select public.sonar_admission_acquire()'));
await identity(a);const cid=sample.candidates[0].candidate_id;
await db.query('select public.sonar_review_save($1,$2,0,$3,$4)',[record.id,cid,'CONFIRMED','checked']);
await assert.rejects(db.query('select public.sonar_review_save($1,$2,0,$3,$4)',[record.id,cid,'FALSE_POSITIVE','stale']));
await db.query('select public.sonar_delete_begin($1)',[record.id]);
await assert.rejects(db.query('select public.sonar_delete_finish($1)',[record.id]));
await db.query('delete from storage.objects where name=$1',[record.image_path]);await db.query('select public.sonar_delete_finish($1)',[record.id]);
await identity('', 'service_role');const lease=(await db.query('select public.sonar_admission_acquire() as value')).rows[0].value;
await assert.rejects(db.exec('select public.sonar_admission_acquire()'));
const uuid=lease.lease_id.replace(/^(.{8})(.{4})(.{4})(.{4})(.{12})$/,'$1-$2-$3-$4-$5');await db.query('select public.sonar_admission_release($1)',[uuid]);
await db.exec('select public.sonar_admission_acquire()');
await db.exec("reset role;update public.sonar_leases set expires_at=now()-interval '1 second';");
const beforeProbe=(await db.query("select jsonb_build_object('settings',(select to_jsonb(s) from public.sonar_settings s),'usage',(select jsonb_agg(to_jsonb(u) order by day) from public.sonar_usage u),'leases',(select jsonb_agg(to_jsonb(l) order by id) from public.sonar_leases l)) as snapshot")).rows[0].snapshot;
const probe=await db.exec(readFileSync('supabase/verification/module1_usage_probe.sql','utf8'));
const checks=probe.find(value=>value.rows?.some(row=>row.check_name==='daily_budget'));assert.equal(checks.rows.length,5);assert.ok(checks.rows.every(row=>row.passed));
const afterProbe=(await db.query("select jsonb_build_object('settings',(select to_jsonb(s) from public.sonar_settings s),'usage',(select jsonb_agg(to_jsonb(u) order by day) from public.sonar_usage u),'leases',(select jsonb_agg(to_jsonb(l) order by id) from public.sonar_leases l)) as snapshot")).rows[0].snapshot;assert.deepEqual(afterProbe,beforeProbe);
await db.close();console.log('SQL tests passed: migration, isolation, storage policies, immutable review conflicts, two-phase deletion and service-only admission.');
