import {PGlite} from '../.temp/supabase-sql-test/node_modules/@electric-sql/pglite/dist/index.js';
import {readFileSync} from 'node:fs';
import assert from 'node:assert/strict';
const db=new PGlite();
await db.exec(`create role anon;create role authenticated;create role service_role;create schema auth;create schema storage;
create table auth.users(id uuid primary key,email text,email_confirmed_at timestamptz);create function auth.uid() returns uuid language sql as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
grant usage on schema auth,storage to authenticated;grant execute on function auth.uid() to authenticated;
create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
create table storage.objects(bucket_id text,name text,primary key(bucket_id,name));alter table storage.objects enable row level security;grant select,insert,delete on storage.objects to authenticated;`);
await db.exec(readFileSync('supabase/migrations/202610020001_sonar_cloud.sql','utf8'));
await db.exec(readFileSync('supabase/migrations/202610040001_judge_demo.sql','utf8'));
const demo='33333333-3333-3333-3333-333333333333',privateUser='11111111-1111-1111-1111-111111111111';
await db.exec(`insert into auth.users values('${demo}','judge.demo@sonarshield.example',now()),('${privateUser}','private@example.test',now());insert into public.sonar_members values('${privateUser}');`);
await db.exec(readFileSync('supabase/verification/activate_judge_demo.sql','utf8'));
async function identity(id,role='authenticated'){await db.exec(`reset role;select set_config('request.jwt.claim.sub','${id}',false);set role ${role};`);}
await identity('','anon');assert.equal((await db.query('select public.sonar_judge_demo_ready() as ready')).rows[0].ready,true);await assert.rejects(db.exec('select * from public.sonar_judge_demo'));
const sample=JSON.parse(readFileSync('frontend/public/contact-105.json','utf8'));
const create=()=>db.query('select public.sonar_record_create($1::jsonb,$2,$3,$4,$5,null) as value',[JSON.stringify(sample),'PRECOMPUTED_EXAMPLE',sample.input.sha256,66818,'image/jpeg']);
await identity(privateUser);const priv=(await create()).rows[0].value;
await identity(demo);assert.equal((await db.query('select public.sonar_record_list() as value')).rows[0].value.records.length,0);await assert.rejects(db.query('select public.sonar_record_get($1)',[priv.id]));
const original=sample.analysis_id;sample.analysis_id='FAKE_DEMO';await assert.rejects(create());sample.analysis_id=original;
const record=(await create()).rows[0].value;await db.query('insert into storage.objects values($1,$2)',['sonar-records',record.image_path]);
assert.equal((await create()).rows[0].value.id,record.id,'reseed is idempotent');
await assert.rejects(db.query('select public.sonar_record_create($1::jsonb,$2,$3,$4,$5,null)',[JSON.stringify(sample),'LIVE_ANALYSIS',sample.input.sha256,66818,'image/jpeg']));
const cid=sample.candidates[0].candidate_id;
await db.query('select public.sonar_review_save($1,$2,0,$3,$4)',[record.id,cid,'NEEDS_INVESTIGATION','demo note']);
await db.query('select public.sonar_review_save($1,$2,1,$3,$4)',[record.id,cid,'NEEDS_INVESTIGATION','judge revision']);
assert.equal((await db.query('select public.sonar_record_get($1) as value',[record.id])).rows[0].value.review_history.length,2);
await assert.rejects(db.query('select public.sonar_review_save($1,$2,2,$3,$4)',[record.id,cid,'CONFIRMED','x'.repeat(2001)]));
await assert.rejects(db.query('select public.sonar_delete_begin($1)',[record.id]));
await assert.rejects(db.query('delete from storage.objects where name=$1',[record.image_path]).then(r=>{assert.equal(r.affectedRows,0);throw Error('delete policy rejects');}));
await identity('', 'service_role');await db.exec('reset role');await assert.rejects(db.exec(`insert into public.sonar_team_members values(gen_random_uuid(),'${demo}')`));
await identity(privateUser);const cidPriv=sample.candidates[0].candidate_id;await db.query('select public.sonar_review_save($1,$2,0,$3,$4)',[priv.id,cidPriv,'NEEDS_INVESTIGATION','private unaffected']);await db.query('select public.sonar_delete_begin($1)',[priv.id]);await db.query('select public.sonar_delete_finish($1)',[priv.id]);
await identity('','service_role');await db.exec(`reset role;update public.sonar_records set expires_at=now()-interval '1 second' where id='${record.id}';delete from storage.objects where name='${record.image_path}';`);await identity('','service_role');await db.query('select public.sonar_prune_record($1)',[record.id]);
await db.close();console.log('Judge SQL: public readiness, sample-only creation, private isolation, revision limits, delete/team guards, ordinary reviewers and maintenance passed.');
