import { Activity, ArrowRight, ClipboardList, Compass, FileText, Radio, ShieldCheck } from 'lucide-react';
import type { AnalyzeResponse, HealthResponse } from '../../types';
import type { HumanReview } from '../../review/reviewStore';
import { mapPoints } from '../map/mapData';

const value = (text: string | number | null | undefined) => text ?? 'NOT AVAILABLE';
export function OverviewPage({ result, reviews, health, onAnalysis, onReports }: { result: AnalyzeResponse | null; reviews: Record<string, HumanReview>; health: HealthResponse | null; onAnalysis: () => void; onReports: () => void }) {
  const reviewed = result?.candidates.filter(candidate => reviews[candidate.candidate_id]?.analysisId === result.analysis_id).length ?? 0;
  const geographic = result ? mapPoints(result.candidates).length : 0;
  return <div className="product-page"><div className="product-page-head"><span className="eyebrow">WORKSPACE OVERVIEW</span><h1>Mission status</h1><p>Current session data from the F8 analysis service.</p></div><div className="overview-grid"><section className="panel overview-lead"><div className="overview-icon"><Compass size={24} /></div><span className="eyebrow">CURRENT ANALYSIS</span><h2>{result ? result.analysis_id : 'No analysis loaded'}</h2><p>{result ? `${result.input.filename} · ${result.processing.status}` : 'Upload a side-scan sonar image to inspect AI candidates and evidence.'}</p><div className="overview-actions"><button className="primary" type="button" onClick={onAnalysis}>Open analysis <ArrowRight size={15} /></button>{result && <button className="secondary" type="button" onClick={onReports}>View report <FileText size={15} /></button>}</div></section><section className="panel overview-stat"><Activity size={19} /><span>CANDIDATES</span><strong>{result ? result.candidates.length : '—'}</strong><small>Current analysis</small></section><section className="panel overview-stat"><ClipboardList size={19} /><span>HUMAN REVIEW</span><strong>{result ? `${reviewed} / ${result.candidates.length}` : '—'}</strong><small>Stored locally in this browser</small></section><section className="panel overview-stat"><Compass size={19} /><span>GEOGRAPHIC</span><strong>{result ? `${geographic} / ${result.candidates.length}` : '—'}</strong><small>Backend supplied coordinates</small></section><section className="panel overview-service"><div><ShieldCheck size={18} /><strong>F8 service</strong></div><span className={health?.status === 'OK' ? 'good' : 'offline'}>{health?.status ?? 'OFFLINE'}</span><p>{health ? `Pipeline ${value(result?.processing.pipeline_version ?? health.pipeline_version)} · ${Object.keys(health.components).length} component states reported` : 'The workspace remains available. Live analysis needs the F8 service.'}</p></section></div></div>;
}

export function SystemPage({ health, busy, onRetry }: { health: HealthResponse | null; busy: boolean; onRetry: () => void }) {
  return <div className="product-page"><div className="product-page-head"><span className="eyebrow">SYSTEM · F8</span><h1>Service status</h1><p>Direct status from the configured backend.</p></div><div className="panel system-panel"><div className="system-overall"><Radio size={19} /><div><span className="eyebrow">API STATUS</span><strong className={health?.status === 'OK' ? 'good' : 'offline'}>{health?.status ?? 'BACKEND OFFLINE'}</strong></div><button type="button" className="secondary" onClick={onRetry} disabled={busy}>{busy ? 'Checking…' : 'Check connection'}</button></div>{health && <div className="system-components">{Object.entries(health.components).map(([name, state]) => <div key={name}><span>{name.replaceAll('_', ' ')}</span><strong className={state === 'READY' ? 'good' : 'offline'}>{state}</strong></div>)}</div>}<div className="system-notes"><h2>Current backend capabilities</h2><p>Full analysis uses <code>/analyze</code>. <code>/detect</code> remains a stub. Human reviews stay in this browser because F8 has no review endpoint. <code>/report</code> returns metadata but no downloadable artifact.</p></div></div></div>;
}
