import { Activity, ArrowRight, ClipboardList, Compass, FileText, Radio, ShieldCheck } from 'lucide-react';
import type { AnalyzeResponse, HealthResponse } from '../../types';
import type { HumanReview } from '../../review/reviewStore';
import { mapPoints } from '../map/mapData';

const value = (text: string | number | null | undefined) => text ?? 'NOT AVAILABLE';
export function OverviewPage({ result, reviews, health, onAnalysis, onReports }: { result: AnalyzeResponse | null; reviews: Record<string, HumanReview>; health: HealthResponse | null; onAnalysis: () => void; onReports: () => void }) {
  const reviewed = result?.candidates.filter(candidate => reviews[candidate.candidate_id]?.analysisId === result.analysis_id).length ?? 0;
  const geographic = result ? mapPoints(result.candidates).length : 0;
  return <div className="product-page"><div className="product-page-head"><span className="eyebrow">WORKSPACE OVERVIEW</span><h1>Mission status</h1><p>Current session data from the analysis Space.</p></div><div className="overview-grid"><section className="panel overview-lead"><div className="overview-icon"><Compass size={24} /></div><span className="eyebrow">CURRENT ANALYSIS</span><h2>{result ? result.analysis_id : 'No analysis loaded'}</h2><p>{result ? `${result.input.filename} · ${result.processing.status}` : 'Upload a side-scan sonar image to inspect AI candidates and evidence.'}</p><div className="overview-actions"><button className="primary" type="button" onClick={onAnalysis}>Open analysis <ArrowRight size={15} /></button>{result && <button className="secondary" type="button" onClick={onReports}>View report <FileText size={15} /></button>}</div></section><section className="panel overview-stat"><Activity size={19} /><span>CANDIDATES</span><strong>{result ? result.candidates.length : '—'}</strong><small>Current analysis</small></section><section className="panel overview-stat"><ClipboardList size={19} /><span>HUMAN REVIEW</span><strong>{result ? `${reviewed} / ${result.candidates.length}` : '—'}</strong><small>Stored locally in this browser</small></section><section className="panel overview-stat"><Compass size={19} /><span>GEOGRAPHIC</span><strong>{result ? `${geographic} / ${result.candidates.length}` : '—'}</strong><small>Backend supplied coordinates</small></section><section className="panel overview-service"><div><ShieldCheck size={18} /><strong>Analysis Space</strong></div><span className={health?.status === 'REACHABLE' ? 'good' : 'offline'}>{health?.status ?? 'OFFLINE'}</span><p>{health ? `Space API reachable; component health is not reported.${result ? ` Analysis pipeline: ${value(result.processing.pipeline_version)}.` : ''}` : 'The workspace remains available. Live analysis needs the Space.'}</p></section></div></div>;
}

export function SystemPage({ health, busy, onRetry }: { health: HealthResponse | null; busy: boolean; onRetry: () => void }) {
  return <div className="product-page"><div className="product-page-head"><span className="eyebrow">SYSTEM · SPACE</span><h1>Service status</h1><p>Connection to the Hugging Face Gradio Space. Reachability does not confirm model readiness.</p></div><div className="panel system-panel"><div className="system-overall"><Radio size={19} /><div><span className="eyebrow">SPACE API</span><strong className={health?.status === 'REACHABLE' ? 'good' : 'offline'}>{health?.status ?? 'SPACE OFFLINE'}</strong></div><button type="button" className="secondary" onClick={onRetry} disabled={busy}>{busy ? 'Checking…' : 'Check connection'}</button></div><div className="system-notes"><h2>Current backend capabilities</h2><p>Live analysis uses Gradio <code>/analyze_image_gradio</code>. The Space does not publish separate health, raw detection, report, or review endpoints. Component health is not reported; human reviews and report exports remain in this browser.</p></div></div></div>;
}
